//go:build !ignore_autogenerated

/*
Copyright 2026 CogitoForge AI.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSpec.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CallbackSpec) DeepCopyInto(out *CallbackSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CallbackSpec.
func (in *CallbackSpec) DeepCopy() *CallbackSpec {
	if in == nil {
		return nil
	}
	out := new(CallbackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewInstallation) DeepCopyInto(out *CogitoReviewInstallation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewInstallation.
func (in *CogitoReviewInstallation) DeepCopy() *CogitoReviewInstallation {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewInstallation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CogitoReviewInstallation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewInstallationList) DeepCopyInto(out *CogitoReviewInstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CogitoReviewInstallation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewInstallationList.
func (in *CogitoReviewInstallationList) DeepCopy() *CogitoReviewInstallationList {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewInstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CogitoReviewInstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewInstallationSpec) DeepCopyInto(out *CogitoReviewInstallationSpec) {
	*out = *in
	out.Images = in.Images
	in.Ingress.DeepCopyInto(&out.Ingress)
	out.Database = in.Database
	out.Redis = in.Redis
	out.Frontend = in.Frontend
	out.Auth = in.Auth
	out.Secrets = in.Secrets
	out.Components = in.Components
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewInstallationSpec.
func (in *CogitoReviewInstallationSpec) DeepCopy() *CogitoReviewInstallationSpec {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewInstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewInstallationStatus) DeepCopyInto(out *CogitoReviewInstallationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		copy(*out, *in)
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]EndpointStatus, len(*in))
		copy(*out, *in)
	}
	if in.AvailableComponents != nil {
		in, out := &in.AvailableComponents, &out.AvailableComponents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewInstallationStatus.
func (in *CogitoReviewInstallationStatus) DeepCopy() *CogitoReviewInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewInstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewRun) DeepCopyInto(out *CogitoReviewRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewRun.
func (in *CogitoReviewRun) DeepCopy() *CogitoReviewRun {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CogitoReviewRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewRunExecution) DeepCopyInto(out *CogitoReviewRunExecution) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewRunExecution.
func (in *CogitoReviewRunExecution) DeepCopy() *CogitoReviewRunExecution {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewRunExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewRunList) DeepCopyInto(out *CogitoReviewRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CogitoReviewRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewRunList.
func (in *CogitoReviewRunList) DeepCopy() *CogitoReviewRunList {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CogitoReviewRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewRunReview) DeepCopyInto(out *CogitoReviewRunReview) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewRunReview.
func (in *CogitoReviewRunReview) DeepCopy() *CogitoReviewRunReview {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewRunReview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewRunSpec) DeepCopyInto(out *CogitoReviewRunSpec) {
	*out = *in
	if in.InstallationRef != nil {
		in, out := &in.InstallationRef, &out.InstallationRef
		*out = new(ResourceRef)
		**out = **in
	}
	if in.RuntimePolicyRef != nil {
		in, out := &in.RuntimePolicyRef, &out.RuntimePolicyRef
		*out = new(ResourceRef)
		**out = **in
	}
	if in.ScalingPolicyRef != nil {
		in, out := &in.ScalingPolicyRef, &out.ScalingPolicyRef
		*out = new(ResourceRef)
		**out = **in
	}
	out.Review = in.Review
	in.Execution.DeepCopyInto(&out.Execution)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewRunSpec.
func (in *CogitoReviewRunSpec) DeepCopy() *CogitoReviewRunSpec {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewRunStatus) DeepCopyInto(out *CogitoReviewRunStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		copy(*out, *in)
	}
	if in.PodRefs != nil {
		in, out := &in.PodRefs, &out.PodRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExitCode != nil {
		in, out := &in.ExitCode, &out.ExitCode
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewRunStatus.
func (in *CogitoReviewRunStatus) DeepCopy() *CogitoReviewRunStatus {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewRuntimePolicy) DeepCopyInto(out *CogitoReviewRuntimePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewRuntimePolicy.
func (in *CogitoReviewRuntimePolicy) DeepCopy() *CogitoReviewRuntimePolicy {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewRuntimePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CogitoReviewRuntimePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewRuntimePolicyList) DeepCopyInto(out *CogitoReviewRuntimePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CogitoReviewRuntimePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewRuntimePolicyList.
func (in *CogitoReviewRuntimePolicyList) DeepCopy() *CogitoReviewRuntimePolicyList {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewRuntimePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CogitoReviewRuntimePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewRuntimePolicySpec) DeepCopyInto(out *CogitoReviewRuntimePolicySpec) {
	*out = *in
	in.Executor.DeepCopyInto(&out.Executor)
	out.Job = in.Job
	out.Resources = in.Resources
	out.Execution = in.Execution
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewRuntimePolicySpec.
func (in *CogitoReviewRuntimePolicySpec) DeepCopy() *CogitoReviewRuntimePolicySpec {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewRuntimePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewRuntimePolicyStatus) DeepCopyInto(out *CogitoReviewRuntimePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewRuntimePolicyStatus.
func (in *CogitoReviewRuntimePolicyStatus) DeepCopy() *CogitoReviewRuntimePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewRuntimePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewScalingPolicy) DeepCopyInto(out *CogitoReviewScalingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewScalingPolicy.
func (in *CogitoReviewScalingPolicy) DeepCopy() *CogitoReviewScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CogitoReviewScalingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewScalingPolicyList) DeepCopyInto(out *CogitoReviewScalingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CogitoReviewScalingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewScalingPolicyList.
func (in *CogitoReviewScalingPolicyList) DeepCopy() *CogitoReviewScalingPolicyList {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewScalingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CogitoReviewScalingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewScalingPolicySpec) DeepCopyInto(out *CogitoReviewScalingPolicySpec) {
	*out = *in
	out.API = in.API
	out.Worker = in.Worker
	out.Execution = in.Execution
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewScalingPolicySpec.
func (in *CogitoReviewScalingPolicySpec) DeepCopy() *CogitoReviewScalingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewScalingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CogitoReviewScalingPolicyStatus) DeepCopyInto(out *CogitoReviewScalingPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CogitoReviewScalingPolicyStatus.
func (in *CogitoReviewScalingPolicyStatus) DeepCopy() *CogitoReviewScalingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CogitoReviewScalingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentReplicaSpec) DeepCopyInto(out *ComponentReplicaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentReplicaSpec.
func (in *ComponentReplicaSpec) DeepCopy() *ComponentReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentScalingSpec) DeepCopyInto(out *ComponentScalingSpec) {
	*out = *in
	out.Autoscaling = in.Autoscaling
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentScalingSpec.
func (in *ComponentScalingSpec) DeepCopy() *ComponentScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentsSpec) DeepCopyInto(out *ComponentsSpec) {
	*out = *in
	out.API = in.API
	out.Worker = in.Worker
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentsSpec.
func (in *ComponentsSpec) DeepCopy() *ComponentsSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRefs) DeepCopyInto(out *CredentialRefs) {
	*out = *in
	out.GitCredentialRef = in.GitCredentialRef
	out.LLMCredentialRef = in.LLMCredentialRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRefs.
func (in *CredentialRefs) DeepCopy() *CredentialRefs {
	if in == nil {
		return nil
	}
	out := new(CredentialRefs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	out.URLSecretRef = in.URLSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointStatus) DeepCopyInto(out *EndpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointStatus.
func (in *EndpointStatus) DeepCopy() *EndpointStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionPolicySpec) DeepCopyInto(out *ExecutionPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionPolicySpec.
func (in *ExecutionPolicySpec) DeepCopy() *ExecutionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionScalingSpec) DeepCopyInto(out *ExecutionScalingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionScalingSpec.
func (in *ExecutionScalingSpec) DeepCopy() *ExecutionScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutorSpec) DeepCopyInto(out *ExecutorSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutorSpec.
func (in *ExecutorSpec) DeepCopy() *ExecutorSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendSpec) DeepCopyInto(out *FrontendSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendSpec.
func (in *FrontendSpec) DeepCopy() *FrontendSpec {
	if in == nil {
		return nil
	}
	out := new(FrontendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.TLSSecretRef != nil {
		in, out := &in.TLSSecretRef, &out.TLSSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationSecretsSpec) DeepCopyInto(out *InstallationSecretsSpec) {
	*out = *in
	out.CallbackSecretRef = in.CallbackSecretRef
	out.SessionSecretRef = in.SessionSecretRef
	out.EncryptionKeySecretRef = in.EncryptionKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationSecretsSpec.
func (in *InstallationSecretsSpec) DeepCopy() *InstallationSecretsSpec {
	if in == nil {
		return nil
	}
	out := new(InstallationSecretsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobCleanupSpec) DeepCopyInto(out *JobCleanupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobCleanupSpec.
func (in *JobCleanupSpec) DeepCopy() *JobCleanupSpec {
	if in == nil {
		return nil
	}
	out := new(JobCleanupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobPolicySpec) DeepCopyInto(out *JobPolicySpec) {
	*out = *in
	out.Cleanup = in.Cleanup
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobPolicySpec.
func (in *JobPolicySpec) DeepCopy() *JobPolicySpec {
	if in == nil {
		return nil
	}
	out := new(JobPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesExecutionInnerSpec) DeepCopyInto(out *KubernetesExecutionInnerSpec) {
	*out = *in
	out.Callback = in.Callback
	out.Workspace = in.Workspace
	out.Credentials = in.Credentials
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesExecutionInnerSpec.
func (in *KubernetesExecutionInnerSpec) DeepCopy() *KubernetesExecutionInnerSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesExecutionInnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisSpec) DeepCopyInto(out *RedisSpec) {
	*out = *in
	out.URLSecretRef = in.URLSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisSpec.
func (in *RedisSpec) DeepCopy() *RedisSpec {
	if in == nil {
		return nil
	}
	out := new(RedisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePair) DeepCopyInto(out *ResourcePair) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePair.
func (in *ResourcePair) DeepCopy() *ResourcePair {
	if in == nil {
		return nil
	}
	out := new(ResourcePair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerConcurrencySpec) DeepCopyInto(out *WorkerConcurrencySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerConcurrencySpec.
func (in *WorkerConcurrencySpec) DeepCopy() *WorkerConcurrencySpec {
	if in == nil {
		return nil
	}
	out := new(WorkerConcurrencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerScalingSpec) DeepCopyInto(out *WorkerScalingSpec) {
	*out = *in
	out.Autoscaling = in.Autoscaling
	out.Concurrency = in.Concurrency
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerScalingSpec.
func (in *WorkerScalingSpec) DeepCopy() *WorkerScalingSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSpec) DeepCopyInto(out *WorkspaceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSpec.
func (in *WorkspaceSpec) DeepCopy() *WorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}
