-- migrate:up
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS pr_url TEXT NOT NULL DEFAULT '';
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS pr_author TEXT NOT NULL DEFAULT '';
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS base_sha TEXT NOT NULL DEFAULT '';
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS base_ref TEXT NOT NULL DEFAULT '';
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS head_ref TEXT NOT NULL DEFAULT '';
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS summary_comment_posted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS inline_comments_posted INT NOT NULL DEFAULT 0;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS inline_comments_skipped INT NOT NULL DEFAULT 0;

-- migrate:down
ALTER TABLE reviews DROP COLUMN IF EXISTS inline_comments_skipped;
ALTER TABLE reviews DROP COLUMN IF EXISTS inline_comments_posted;
ALTER TABLE reviews DROP COLUMN IF EXISTS summary_comment_posted;
ALTER TABLE reviews DROP COLUMN IF EXISTS head_ref;
ALTER TABLE reviews DROP COLUMN IF EXISTS base_ref;
ALTER TABLE reviews DROP COLUMN IF EXISTS base_sha;
ALTER TABLE reviews DROP COLUMN IF EXISTS pr_author;
ALTER TABLE reviews DROP COLUMN IF EXISTS pr_url;
