from coreview_shared.llm.opencode import OpenCodeLLMProvider
from coreview_shared.protocols import PRContext, PRMetadata, ReviewFinding

from app.services.review_format import (
    NEXO_COREVIEW_REPO_URL,
    format_summary_comment,
    split_findings,
)


def test_opencode_parse_findings_from_json() -> None:
    provider = OpenCodeLLMProvider(
        agent="code-reviewer",
        model="anthropic/claude-sonnet-4-5",
        timeout_seconds=60,
    )
    data = {
        "findings": [
            {
                "severity": "warning",
                "title": "Missing null check",
                "body": "Variable may be None",
                "file_path": "app/main.py",
                "line_start": 10,
            }
        ]
    }
    findings = provider._parse_findings(data)
    assert len(findings) == 1
    assert findings[0].severity == "warning"
    assert findings[0].file_path == "app/main.py"


def test_opencode_build_command_includes_log_flags() -> None:
    provider = OpenCodeLLMProvider(
        agent="code-reviewer",
        model="openai-compat/gpt-4o",
        timeout_seconds=60,
        log_level="DEBUG",
    )
    cmd = provider._build_command("/workspaces/r1/repo")
    assert cmd[:5] == [
        "opencode",
        "--log-level",
        "DEBUG",
        "--print-logs",
        "run",
    ]
    assert "--format" in cmd
    assert cmd[cmd.index("--format") + 1] == "json"


def test_opencode_slim_prompt_includes_pr_context_and_schema() -> None:
    provider = OpenCodeLLMProvider(
        agent="code-reviewer",
        model="test/model",
        timeout_seconds=60,
    )
    context = PRContext(
        metadata=PRMetadata(
            repo_full_name="org/repo",
            pr_number=1,
            title="Test",
            author="dev",
            head_sha="a" * 40,
            base_sha="b" * 40,
            head_ref="feature",
            base_ref="main",
            html_url="https://github.com/org/repo/pull/1",
        ),
        diff="diff content",
    )
    prompt = provider._build_prompt(context)
    assert "Review pull request #1: Test" in prompt
    assert "org/repo" in prompt
    assert '"findings"' in prompt
    assert "diff content" not in prompt
    assert "Focus on bugs, security, performance" not in prompt


def test_opencode_parse_ndjson_stream_ignores_tool_events() -> None:
    provider = OpenCodeLLMProvider(
        agent="code-reviewer",
        model="test/model",
        timeout_seconds=60,
    )
    stdout = "\n".join(
        [
            '{"type":"step_start","part":{"type":"step-start"}}',
            (
                '{"type":"tool_use","part":{"type":"tool",'
                '"tool":"coreview_coreview-ci_get_summary","output":"{}"}}'
            ),
            (
                '{"type":"text","part":{"type":"text","text":'
                '"```json\\n{\\"findings\\": [{\\"severity\\": \\"warning\\", '
                '\\"title\\": \\"Bug\\", \\"body\\": \\"details\\"}]}\\n```"}}'
            ),
        ]
    )
    findings = provider._parse_cli_output(stdout)
    assert len(findings) == 1
    assert findings[0].title == "Bug"


def test_opencode_parse_ndjson_stream_without_findings_returns_empty() -> None:
    provider = OpenCodeLLMProvider(
        agent="code-reviewer",
        model="test/model",
        timeout_seconds=60,
    )
    stdout = (
        '{"type":"tool_use","part":{"type":"tool","output":"ignored"}}\n'
        '{"type":"step_finish","part":{"type":"step-finish"}}'
    )
    assert provider._parse_cli_output(stdout) == []


def test_split_findings() -> None:
    findings = [
        ReviewFinding(
            severity="warning",
            title="Bug",
            body="details",
            file_path="a.py",
            line_start=5,
        ),
        ReviewFinding(
            severity="info",
            title="Note",
            body="general",
        ),
    ]
    inline, summary = split_findings(findings)
    assert len(inline) == 1
    assert inline[0].path == "a.py"
    assert len(summary) == 1
    assert summary[0].title == "Note"


def test_format_summary_comment_includes_attribution() -> None:
    summary = format_summary_comment([], "org/repo", 7)
    assert "Nexo Co-Review" in summary
    assert NEXO_COREVIEW_REPO_URL in summary
    assert summary.endswith(
        f"*Review generated by [Nexo Co-Review]({NEXO_COREVIEW_REPO_URL}).*"
    )

    with_findings = format_summary_comment(
        [
            ReviewFinding(
                severity="warning",
                title="Bug",
                body="**Problem:** x\n\n**Impact:** y\n\n**Recommendation:** z",
            )
        ],
        "org/repo",
        7,
    )
    assert NEXO_COREVIEW_REPO_URL in with_findings
