/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstallRouteImport } from './routes/install'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews/index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as LlmProvidersIndexRouteImport } from './routes/llm-providers/index'
import { Route as SettingsIdentityProviderRouteImport } from './routes/settings/identity-provider'
import { Route as ReviewsReviewIdRouteImport } from './routes/reviews/$reviewId'
import { Route as RepositoriesRepoIdRouteImport } from './routes/repositories/$repoId'
import { Route as LlmProvidersProviderIdRouteImport } from './routes/llm-providers/$providerId'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams/$teamId/index'
import { Route as TeamsTeamIdReposRepoIdRouteImport } from './routes/teams/$teamId/repos/$repoId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmProvidersIndexRoute = LlmProvidersIndexRouteImport.update({
  id: '/llm-providers/',
  path: '/llm-providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIdentityProviderRoute =
  SettingsIdentityProviderRouteImport.update({
    id: '/settings/identity-provider',
    path: '/settings/identity-provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReviewsReviewIdRoute = ReviewsReviewIdRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRepoIdRoute = RepositoriesRepoIdRouteImport.update({
  id: '/repositories/$repoId',
  path: '/repositories/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmProvidersProviderIdRoute = LlmProvidersProviderIdRouteImport.update({
  id: '/llm-providers/$providerId',
  path: '/llm-providers/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/teams/$teamId/',
  path: '/teams/$teamId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdReposRepoIdRoute = TeamsTeamIdReposRepoIdRouteImport.update({
  id: '/teams/$teamId/repos/$repoId',
  path: '/teams/$teamId/repos/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/llm-providers/$providerId': typeof LlmProvidersProviderIdRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/settings/identity-provider': typeof SettingsIdentityProviderRoute
  '/llm-providers/': typeof LlmProvidersIndexRoute
  '/members/': typeof MembersIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/repos/$repoId': typeof TeamsTeamIdReposRepoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/llm-providers/$providerId': typeof LlmProvidersProviderIdRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/settings/identity-provider': typeof SettingsIdentityProviderRoute
  '/llm-providers': typeof LlmProvidersIndexRoute
  '/members': typeof MembersIndexRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/users': typeof UsersIndexRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/repos/$repoId': typeof TeamsTeamIdReposRepoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/llm-providers/$providerId': typeof LlmProvidersProviderIdRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/settings/identity-provider': typeof SettingsIdentityProviderRoute
  '/llm-providers/': typeof LlmProvidersIndexRoute
  '/members/': typeof MembersIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/repos/$repoId': typeof TeamsTeamIdReposRepoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/install'
    | '/login'
    | '/llm-providers/$providerId'
    | '/repositories/$repoId'
    | '/reviews/$reviewId'
    | '/settings/identity-provider'
    | '/llm-providers/'
    | '/members/'
    | '/repositories/'
    | '/reviews/'
    | '/settings/'
    | '/teams/'
    | '/users/'
    | '/teams/$teamId/'
    | '/teams/$teamId/repos/$repoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/install'
    | '/login'
    | '/llm-providers/$providerId'
    | '/repositories/$repoId'
    | '/reviews/$reviewId'
    | '/settings/identity-provider'
    | '/llm-providers'
    | '/members'
    | '/repositories'
    | '/reviews'
    | '/settings'
    | '/teams'
    | '/users'
    | '/teams/$teamId'
    | '/teams/$teamId/repos/$repoId'
  id:
    | '__root__'
    | '/'
    | '/install'
    | '/login'
    | '/llm-providers/$providerId'
    | '/repositories/$repoId'
    | '/reviews/$reviewId'
    | '/settings/identity-provider'
    | '/llm-providers/'
    | '/members/'
    | '/repositories/'
    | '/reviews/'
    | '/settings/'
    | '/teams/'
    | '/users/'
    | '/teams/$teamId/'
    | '/teams/$teamId/repos/$repoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  LlmProvidersProviderIdRoute: typeof LlmProvidersProviderIdRoute
  RepositoriesRepoIdRoute: typeof RepositoriesRepoIdRoute
  ReviewsReviewIdRoute: typeof ReviewsReviewIdRoute
  SettingsIdentityProviderRoute: typeof SettingsIdentityProviderRoute
  LlmProvidersIndexRoute: typeof LlmProvidersIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
  TeamsTeamIdReposRepoIdRoute: typeof TeamsTeamIdReposRepoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-providers/': {
      id: '/llm-providers/'
      path: '/llm-providers'
      fullPath: '/llm-providers/'
      preLoaderRoute: typeof LlmProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/identity-provider': {
      id: '/settings/identity-provider'
      path: '/settings/identity-provider'
      fullPath: '/settings/identity-provider'
      preLoaderRoute: typeof SettingsIdentityProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewId': {
      id: '/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof ReviewsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repoId': {
      id: '/repositories/$repoId'
      path: '/repositories/$repoId'
      fullPath: '/repositories/$repoId'
      preLoaderRoute: typeof RepositoriesRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-providers/$providerId': {
      id: '/llm-providers/$providerId'
      path: '/llm-providers/$providerId'
      fullPath: '/llm-providers/$providerId'
      preLoaderRoute: typeof LlmProvidersProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/repos/$repoId': {
      id: '/teams/$teamId/repos/$repoId'
      path: '/teams/$teamId/repos/$repoId'
      fullPath: '/teams/$teamId/repos/$repoId'
      preLoaderRoute: typeof TeamsTeamIdReposRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  LlmProvidersProviderIdRoute: LlmProvidersProviderIdRoute,
  RepositoriesRepoIdRoute: RepositoriesRepoIdRoute,
  ReviewsReviewIdRoute: ReviewsReviewIdRoute,
  SettingsIdentityProviderRoute: SettingsIdentityProviderRoute,
  LlmProvidersIndexRoute: LlmProvidersIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
  TeamsTeamIdReposRepoIdRoute: TeamsTeamIdReposRepoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
