from __future__ import annotations

import asyncio
import json
import logging
from datetime import UTC, datetime

import httpx
from coreview_shared.auth.callback_hmac import sign_payload
from coreview_shared.git.models import InlineComment
from coreview_shared.review import ReviewFinding
from coreview_shared.schemas.review_callback import (
    ReviewCallbackAgent,
    ReviewCallbackError,
    ReviewCallbackEvent,
    ReviewCallbackEventType,
    ReviewCallbackFinding,
    ReviewCallbackGithubResult,
    ReviewCallbackResult,
)

from app.config import get_settings
from app.services.models import ReviewPublishResult, ReviewRunContext

logger = logging.getLogger(__name__)

COGITO_REVIEW_REPO_URL = "https://github.com/CogitoForge-AI/cogito-review"
SIGNATURE_HEADER = "X-Review-Signature-256"
MAX_RETRIES = 3
RETRY_BACKOFF_SECONDS = (1.0, 2.0, 4.0)
_REVIEW_ATTRIBUTION_FOOTER = (
    f"\n\n---\n\n*Review generated by [Cogito Review]({COGITO_REVIEW_REPO_URL}).*"
)


def _parse_callback_metadata(raw: str) -> dict:
    if not raw.strip():
        return {}
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        logger.warning("Invalid COGITO_REVIEW_CALLBACK_METADATA JSON; using empty dict")
        return {}
    return parsed if isinstance(parsed, dict) else {}


def _findings_to_callback(
    findings: list[ReviewFinding],
) -> list[ReviewCallbackFinding]:
    return [
        ReviewCallbackFinding(
            severity=f.severity,
            title=f.title,
            body=f.body,
            file_path=f.file_path,
            line_start=f.line_start,
            line_end=f.line_end,
        )
        for f in findings
    ]


def _split_findings(
    findings: list[ReviewFinding],
) -> tuple[list[InlineComment], list[ReviewFinding]]:
    inline: list[InlineComment] = []
    summary_only: list[ReviewFinding] = []
    for finding in findings:
        if finding.file_path and finding.line_start:
            body = f"**[{finding.severity.upper()}] {finding.title}**\n\n{finding.body}"
            inline.append(
                InlineComment(
                    path=finding.file_path,
                    line=finding.line_start,
                    body=body,
                )
            )
            continue
        summary_only.append(finding)
    return inline, summary_only


def _summary_findings(
    findings: list[ReviewFinding],
    posted_inline: tuple[InlineComment, ...],
) -> list[ReviewFinding]:
    posted_keys = {(comment.path, comment.line) for comment in posted_inline}
    return [
        finding
        for finding in findings
        if not (
            finding.file_path
            and finding.line_start
            and (finding.file_path, finding.line_start) in posted_keys
        )
    ]


def _format_summary_comment(
    findings: list[ReviewFinding],
    repo_full_name: str,
    pr_number: int,
) -> str:
    if not findings:
        return (
            f"## Cogito Review — {repo_full_name}#{pr_number}\n\n"
            "No issues found. LGTM!"
            f"{_REVIEW_ATTRIBUTION_FOOTER}"
        )
    lines = [f"## Cogito Review — {repo_full_name}#{pr_number}\n"]
    for finding in findings:
        loc = ""
        if finding.file_path:
            loc = f" (`{finding.file_path}`"
            if finding.line_start:
                loc += f":{finding.line_start}"
            loc += ")"
        lines.append(
            f"### [{finding.severity.upper()}] {finding.title}{loc}\n{finding.body}\n"
        )
    return "\n".join(lines) + _REVIEW_ATTRIBUTION_FOOTER


class _ReviewCallbackClient:
    def __init__(self, context: ReviewRunContext) -> None:
        settings = context.settings
        self._url = settings.callback_url
        self._secret = settings.callback_secret
        self._metadata = _parse_callback_metadata(settings.callback_metadata)
        self._agent = ReviewCallbackAgent(
            name="cogito-review-agent",
            version=get_settings().app_version,
        )

    def build_event(
        self,
        event: ReviewCallbackEventType,
        *,
        context: ReviewRunContext,
        result: ReviewCallbackResult | None = None,
        error: ReviewCallbackError | None = None,
    ) -> ReviewCallbackEvent:
        return ReviewCallbackEvent(
            event=event,
            review_id=context.review_id,
            occurred_at=datetime.now(tz=UTC),
            agent=self._agent,
            request=context.callback_request,
            result=result,
            error=error,
            metadata=dict(self._metadata),
        )

    async def post_event(self, payload: ReviewCallbackEvent) -> None:
        body = json.dumps(
            payload.model_dump(mode="json"),
            separators=(",", ":"),
        ).encode()
        headers = {
            "Content-Type": "application/json",
            SIGNATURE_HEADER: sign_payload(body, self._secret),
        }

        last_error: Exception | None = None
        for attempt, delay in enumerate(RETRY_BACKOFF_SECONDS):
            try:
                async with httpx.AsyncClient(timeout=30.0) as client:
                    response = await client.post(
                        self._url,
                        content=body,
                        headers=headers,
                    )
                if response.status_code < 500:
                    if response.status_code >= 400:
                        msg = (
                            f"Review callback rejected ({response.status_code}): "
                            f"{response.text[:200]}"
                        )
                        raise RuntimeError(msg)
                    return
                last_error = RuntimeError(
                    f"Review callback server error ({response.status_code})"
                )
            except httpx.HTTPError as exc:
                last_error = exc

            if attempt < len(RETRY_BACKOFF_SECONDS) - 1:
                logger.warning(
                    "Review callback attempt %d failed; retrying in %.1fs",
                    attempt + 1,
                    delay,
                )
                await asyncio.sleep(delay)

        msg = f"Review callback failed after {MAX_RETRIES} attempts"
        raise RuntimeError(msg) from last_error


class ReviewReporter:
    def __init__(self) -> None:
        self._clients: dict[str, _ReviewCallbackClient] = {}

    def _client(self, context: ReviewRunContext) -> _ReviewCallbackClient:
        client = self._clients.get(context.review_id)
        if client is None:
            client = _ReviewCallbackClient(context)
            self._clients[context.review_id] = client
        return client

    async def send_callback(
        self,
        event: ReviewCallbackEventType,
        context: ReviewRunContext,
        *,
        findings: list[ReviewFinding] | None = None,
        publish_result: ReviewPublishResult | None = None,
        error: Exception | None = None,
    ) -> None:
        result = None
        callback_error = None
        if findings is not None:
            stats = publish_result or ReviewPublishResult(findings=tuple(findings))
            result = ReviewCallbackResult(
                findings=_findings_to_callback(findings),
                github=ReviewCallbackGithubResult(
                    summary_comment_posted=stats.summary_comment_posted,
                    inline_comments_posted=stats.inline_comments_posted,
                    inline_comments_skipped=stats.inline_comments_skipped,
                ),
            )
        if error is not None:
            callback_error = ReviewCallbackError(message=str(error))

        payload = self._client(context).build_event(
            event,
            context=context,
            result=result,
            error=callback_error,
        )
        await self._client(context).post_event(payload)

    async def post_comments(
        self,
        context: ReviewRunContext,
        findings: list[ReviewFinding],
    ) -> ReviewPublishResult:
        if context.prepared_review is None:
            msg = "Review context is missing prepared review"
            raise RuntimeError(msg)

        inline_comments, _ = _split_findings(findings)
        posted_inline: tuple[InlineComment, ...] = ()
        inline_skipped = 0
        if inline_comments:
            inline_result = await context.providers.git.publish_inline_comments(
                context.prepared_review,
                inline_comments,
            )
            posted_inline = inline_result.posted
            inline_skipped = len(inline_result.skipped)
            if inline_result.skipped:
                logger.info(
                    "Review %s: %d inline comment(s) moved to summary (not in diff)",
                    context.review_id,
                    inline_skipped,
                )

        summary_findings = _summary_findings(findings, posted_inline)
        summary = _format_summary_comment(
            summary_findings,
            context.settings.repo_full_name,
            context.settings.pr_number,
        )
        await context.providers.git.publish_summary_comment(
            context.prepared_review,
            summary,
        )
        return ReviewPublishResult(
            findings=tuple(findings),
            posted_inline_comments=posted_inline,
            inline_comments_posted=len(posted_inline),
            inline_comments_skipped=inline_skipped,
            summary_comment_posted=True,
        )
